# Generated by Django 4.2.6 on 2023-10-05 07:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hotel",
            old_name="hotel_descritption",
            new_name="hotel_description",
        ),
    ]
