# Generated by Django 4.2.5 on 2023-10-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipe", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipe",
            name="receipe_image",
        ),
        migrations.AddField(
            model_name="receipe",
            name="receipe_link",
            field=models.CharField(default=500, max_length=500),
        ),
    ]
