# Generated by Django 4.2.5 on 2023-10-18 04:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("receipe", "0002_remove_receipe_receipe_image_receipe_receipe_link"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Receipe",
            new_name="Shedule",
        ),
    ]
