# Generated by Django 4.2.5 on 2023-10-18 08:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("receipe", "0003_rename_receipe_shedule"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shedule",
            old_name="receipe_link",
            new_name="class_link",
        ),
        migrations.RenameField(
            model_name="shedule",
            old_name="receipe_view_count",
            new_name="class_view_count",
        ),
        migrations.RenameField(
            model_name="shedule",
            old_name="receipe_description",
            new_name="subject_description",
        ),
        migrations.RenameField(
            model_name="shedule",
            old_name="receipe_name",
            new_name="subject_name",
        ),
    ]
