# Generated by Django 4.2.6 on 2023-10-10 07:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hotel",
            old_name="price",
            new_name="hotel_price",
        ),
    ]
