# Generated by Django 4.2.6 on 2023-10-10 07:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_rename_price_hotel_hotel_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hotel",
            old_name="hotel_price",
            new_name="price",
        ),
    ]
