# Generated by Django 4.2.6 on 2023-10-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0003_rename_hotel_price_hotel_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_name", models.CharField(max_length=100)),
                ("job_description", models.TextField()),
                ("experience", models.IntegerField()),
                ("emenities", models.ManyToManyField(to="book.emenitites")),
            ],
        ),
        migrations.DeleteModel(
            name="Hotel",
        ),
    ]
