# Generated by Django 4.2.5 on 2023-10-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipe", "0002_blood"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipe",
            name="receipe_image",
        ),
        migrations.AddField(
            model_name="receipe",
            name="receipe_date",
            field=models.CharField(default="name", max_length=100),
        ),
    ]
