# Generated by Django 4.2.5 on 2023-10-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipe", "0004_receipe_receipe_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipe",
            name="receipe_fill",
            field=models.CharField(default="gfg", max_length=100),
        ),
    ]
