# Generated by Django 4.2.5 on 2023-10-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipe", "0005_receipe_receipe_fill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blood",
            name="blood_image",
        ),
        migrations.AddField(
            model_name="blood",
            name="blood_age",
            field=models.CharField(default="gfg", max_length=100),
        ),
        migrations.AddField(
            model_name="blood",
            name="blood_date",
            field=models.CharField(default="name", max_length=100),
        ),
        migrations.AddField(
            model_name="blood",
            name="blood_fill",
            field=models.CharField(default="gfg", max_length=100),
        ),
    ]
