# Generated by Django 4.2.5 on 2023-10-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipe", "0007_alter_blood_blood_age_alter_blood_blood_fill_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipe",
            name="receipe_status",
            field=models.CharField(default="Pending", max_length=100),
        ),
    ]
