# Generated by Django 4.2.5 on 2023-10-24 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("receipe", "0010_blood_blood_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blood1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blood1_name", models.CharField(max_length=100)),
                ("blood1_description", models.TextField()),
                ("blood1_reason", models.CharField(default="name", max_length=100)),
                ("blood1_age", models.CharField(default="name", max_length=100)),
                ("blood1_fill", models.CharField(default="name", max_length=100)),
                (
                    "blood1_status",
                    models.CharField(
                        blank=True, default="Pending", max_length=100, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Receipe",
        ),
    ]
