# Generated by Django 4.2.5 on 2023-09-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vege", "0009_receipe_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipe",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="student",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
