# Generated by Django 4.2.6 on 2023-10-06 18:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("task_management", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Receipe",
            new_name="task",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="receipe_description",
            new_name="task_description",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="receipe_image",
            new_name="task_image",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="receipe_name",
            new_name="task_name",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="receipe_view_count",
            new_name="task_view_count",
        ),
    ]
