# Generated by Django 4.2.6 on 2023-10-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_events_event_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="event_date",
            field=models.IntegerField(),
        ),
    ]
