# Generated by Django 4.2.6 on 2023-10-22 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0005_alter_events_event_accept"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leaves",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("leave_description", models.TextField()),
                ("leave_date", models.IntegerField()),
                (
                    "leave_accept",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("event_view_count", models.PositiveIntegerField(default=1)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Events",
        ),
    ]
