# Generated by Django 4.2.6 on 2023-10-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_leaves_delete_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaves",
            name="name",
            field=models.CharField(default="Default Name", max_length=100),
        ),
    ]
