# Generated by Django 4.2.6 on 2023-10-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_alter_leaves_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaves",
            name="name",
            field=models.CharField(default="Name", max_length=100),
        ),
    ]
