# Generated by Django 4.2.6 on 2023-10-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.CharField(max_length=500)),
                ("pincode", models.CharField(max_length=10)),
                ("lat", models.CharField(blank=True, max_length=20, null=True)),
                ("lon", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
