# Generated by Django 4.2.5 on 2023-09-27 10:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_car_delete_product"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Car",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
