# Generated by Django 4.2.6 on 2023-10-08 20:10

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("hone", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="color",
            managers=[
                ("everything", django.db.models.manager.Manager()),
            ],
        ),
    ]
