# Generated by Django 4.2.6 on 2023-10-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_pizza_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pizza",
            name="images",
            field=models.CharField(max_length=500),
        ),
    ]
