# Generated by Django 4.2.6 on 2023-10-12 10:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_rename_pizza_book_rename_pizzacategory_bookcategory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="pizza_name",
            new_name="book_name",
        ),
    ]
