# Generated by Django 4.2.6 on 2023-10-14 07:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_rename_pizza_cartitems_book"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Book",
            new_name="Movie",
        ),
    ]
