# Generated by Django 4.2.6 on 2023-10-14 07:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_rename_book_movie"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BookCategory",
            new_name="MovieCategory",
        ),
    ]
