# Generated by Django 4.2.6 on 2023-10-14 07:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_rename_book_cartitems_movie"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="book_name",
            new_name="movie_name",
        ),
    ]
